version: "3"
services:
  opcua-python-server:
    container_name: opc-server
    build: .
    volumes:
      - ./server:/usr/opc
    command: tail -f /dev/null
    ports:
      - 4880:4881
  opcua-python-client:
    container_name: opc-client
    build: .
    volumes:
      - ./client:/usr/opc
    command: tail -f /dev/null
    ports:
      - 4990:4991
